### ISSUE TITLE
Issue with npm install

### ISSUE THREAD

**Issue by sasayd** [sassoftware/sas-visualanalytics-geowebmap#10]
Hi,

  I installed NodeJS,
$ node --version
v14.5.0

Next I tried to run the command 
$npm install
but the following errors occurred.  Do I need to install some dependencies?  
Thanks, Annette  

*partial log:
3326 warn @theintern/istanbul-loader@1.0.0-beta.2 requires a peer of istanbul-lib-instrument@^1.0.0 but none is installed. You must install peer dependencies yourself.
3327 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
3328 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
3329 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
3329 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
3329 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
3329 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
3330 verbose stack Error: node-sass@4.13.0 postinstall: `node scripts/build.js`
3330 verbose stack Exit status 1
3330 verbose stack     at EventEmitter.<anonymous> (/home/ladmin/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
3330 verbose stack     at EventEmitter.emit (events.js:314:20)
3330 verbose stack     at ChildProcess.<anonymous> (/home/ladmin/.nvm/versions/node/v14.5.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
3330 verbose stack     at ChildProcess.emit (events.js:314:20)
3330 verbose stack     at maybeClose (internal/child_process.js:1051:16)
3330 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
3331 verbose pkgid node-sass@4.13.0
3332 verbose cwd /home/ladmin/sas-visualanalytics-geowebmap
3333 verbose Linux 3.10.0-1127.8.2.el7.x86_64
3334 verbose argv "/home/ladmin/.nvm/versions/node/v14.5.0/bin/node" "/home/ladmin/.nvm/versions/node/v14.5.0/bin/npm" "install"
3335 verbose node v14.5.0
3336 verbose npm  v6.14.5
3337 error code ELIFECYCLE
3338 error errno 1
3339 error node-sass@4.13.0 postinstall: `node scripts/build.js`
3339 error Exit status 1
3340 error Failed at the node-sass@4.13.0 postinstall script.
3340 error This is probably not a problem with npm. There is likely additional logging output above.
3341 verbose exit [ 1, true ]

**Comment by tograh** [comment]
sasayd encountered issues doing an npm build from a cloud-hosted vm that were related to the environment.  We discussed the issue over the phone, and I'm closing this issue with her agreement.
